name: Globus-Systems
on:
  schedule:
    # Monday 8:35 UTC or 04:35 EDT
    - cron: '35 8 * * 1'

jobs:
  perlmutter-test:
    uses: SCOREC/github-actions/.github/workflows/globus-test.yml@main
    secrets: inherit
    with:
      machine: "perlmutter"
